### ISSUE TITLE
Прикрутить ORM

### ISSUE THREAD

**Issue by blackbass1988** [fliptheweb/vldc.ru#18]
Пожалуй, sequelizejs, выглядит достойно. плюс там из коробки миграции есть

**Comment by neoascetic** [comment]
[Здесь](https://github.com/fliptheweb/vldc.ru/blob/develop/app.js#L58) и [здесь](https://github.com/fliptheweb/vldc.ru/blob/develop/app.js#L80) угрозы SQL-инъекции

**Comment by blackbass1988** [comment]
a теперЬ?)

**Comment by neoascetic** [comment]
Читабельней и безопасней использовать [параметризуемые запросы](https://github.com/brianc/node-postgres/wiki/Prepared-Statements#parameterized-queries)

**Comment by blackbass1988** [comment]
полностью согласен, но это не сочетается никак с этой задачей. Мне кажется, что на данном этапе в "прикрутить орм" текущий код ок
