### ISSUE TITLE
Поддержка node 0.10 и express 3.x

### ISSUE THREAD

**Issue by Nemoden** [fliptheweb/vldc.ru#5]
https://github.com/Nemoden/vldc.ru/tree/node-0.10

не знаю, как бранч запуллить, оставлю просто тут :)
Там еще атавизмы есть, правда, но итак работает.

дополнительно запилил установку через `package.json` - так ведь кошерней чем все зависимости вручную подсасывать.

**Comment by fliptheweb** [comment]
Попробуй пул реквест сделать?

**Comment by fliptheweb** [comment]
К пятнице Валера обещал нарисовать дизайн странички на влдц, так что на след неделе можно будет запилить все.

**Comment by Nemoden** [comment]
Ну я могу пулл-реквест к девелопу сделать, но я-то хотел новый бранч для аппрува, хотя если хочешь, могу сделать в девелоп пулл реквест :)

**Comment by fliptheweb** [comment]
давай в девелоп

**Comment by Nemoden** [comment]
merged.
